DROP TABLE IF EXISTS LINK_TAGS;
DROP TABLE IF EXISTS TAGS;

CREATE TABLE TAGS (
  TAG_ID   BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
  TAG_NAME VARCHAR(255) NOT NULL,
  UNIQUE (TAG_NAME)
)ENGINE = InnoDB;

CREATE TABLE LINK_TAGS (
  ACCOUNT_ID INT(11)              NOT NULL,
  TAG_ID     BIGINT(10)           NOT NULL,
  SGUID      CHAR(36)
             CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (ACCOUNT_ID, TAG_ID, SGUID),
  CONSTRAINT FK_LINK_TAGS_TO_ACCOUNTS FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  CONSTRAINT FK_LINK_TAGS_TO_TAGS FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID),
  CONSTRAINT FK_LINK_TAGS_TO_SHORTENED_LINKS FOREIGN KEY (SGUID) REFERENCES SHORTENED_LINKS (SGUID)
)ENGINE = InnoDB;




