SELECT
  U.TYPE           AS TYPE,
  U.GEO_LINKS      AS GEO_LINKS,
  U.CAMPAIGN_NAME  AS CAMPAIGN_NAME,
  U.UGUID          AS UGUID,
  U.HASH           AS HASH,
  U.ALIAS          AS ALIAS,
  U.ORIGINAL_URL   AS ORIGINAL_URL,
  U.CUSTOM_DOMAIN  AS CUSTOM_DOMAIN,
  U.CAMPAIGN_ID    AS CAMPAIGN_ID,
  U.CREATION_DATE  AS CREATION_DATE,
  SUM(AGGR.CLICKS) AS CLICKS
FROM UGUID AS AGGR RIGHT JOIN VIEW_UGUID AS U ON AGGR.UGUID = U.UGUID
                                                 AND
                                                 AGGR.DATE BETWEEN '2014-10-13' AND '2014-11-11'
WHERE
  U.CAMPAIGN_ID = 5
  AND U.CAMPAIGN_ARCHIVED = 0
  AND U.LINK_ARCHIVED = 0
  AND (U.ORIGINAL_URL LIKE '%%')
GROUP BY U.UGUID
ORDER BY CLICKS DESC;