SELECT COUNT(0) AS COUNT
FROM (
       SELECT U.UGUID
       FROM UGUID AS AGGR RIGHT JOIN VIEW_UGUID AS U ON AGGR.UGUID = U.UGUID
                                                        AND
                                                        AGGR.DATE BETWEEN '2014-10-13' AND '2014-11-11'
       WHERE
         U.CAMPAIGN_ID = 5
         AND U.CAMPAIGN_ARCHIVED = 0
         AND U.LINK_ARCHIVED = 0
         AND (U.HASH LIKE '%d31%' OR U.ALIAS LIKE '%d31%' OR U.ORIGINAL_URL LIKE '%d31%')
       GROUP BY U.UGUID
     ) AS T;

SELECT
  U.TYPE           AS TYPE,
  U.GEO_LINKS      AS GEO_LINKS,
  U.CAMPAIGN_NAME  AS CAMPAIGN_NAME,
  U.UGUID          AS UGUID,
  U.HASH           AS HASH,
  U.ALIAS          AS ALIAS,
  U.ORIGINAL_URL   AS ORIGINAL_URL,
  U.CUSTOM_DOMAIN  AS CUSTOM_DOMAIN,
  U.CAMPAIGN_ID    AS CAMPAIGN_ID,
  U.CREATION_DATE  AS CREATION_DATE,
  SUM(AGGR.CLICKS) AS CLICKS
FROM UGUID AS AGGR RIGHT JOIN VIEW_UGUID AS U ON AGGR.UGUID = U.UGUID
                                                 AND
                                                 AGGR.DATE BETWEEN '2014-10-13' AND '2014-11-11'
WHERE
  U.CAMPAIGN_ID = 5
  AND U.CAMPAIGN_ARCHIVED = 0
  AND U.LINK_ARCHIVED = 0
  AND (U.HASH LIKE '%d31%' OR U.ALIAS LIKE '%d31%' OR U.ORIGINAL_URL LIKE '%d31%')
GROUP BY U.UGUID
ORDER BY CREATION_DATE DESC, ORDER_INSERTED DESC
LIMIT 0, 20
